function [kprim1, kprim1_pm, kprim2, kprim3, kprim4, kadj1, kadj2, kadj3, kadj4] = ...
    eigenfunctions_cylinder()

kprim1 = @(n, k, l, r, phi, z) besselj(n,k.*r).*exp(1j.*n.*phi).*sin(l.*z);
kprim1_pm = @(n, k, l, r, phi, z) besselj(n,k.*r).*exp(1j.*n.*phi).*sin(l.*z) + ...
    (-1)^(n)*besselj(n,k.*r).*exp(-1j.*n.*phi).*sin(l.*z);


% kprim1 = @(n, k, l, r, phi, z) besselj(n,k.*r).*cos(n.*phi).*sin(l.*z);
kprim2 = @(n, k, l, r, phi, z) -diff.D.*k.*0.5.*(besselj(n-1,k.*r) ...
    - besselj(n+1,k.*r)).*exp(1j.*n.*phi).*sin(l.*z);
kprim3 = @(n, k, l, r, phi, z) -diff.D.*(1./r).*(1j.*n).*besselj(n,k.*r).*...
    exp(1j.*n.*phi).*sin(l.*z);
kprim4 = @(n, k, l, r, phi, z) -diff.D.*besselj(n,k.*r).*...
    exp(1j.*n.*phi).*l.*cos(l.*z);

kadj1 = @(n, k, l, r, phi, z) k.*0.5.*(besselj(n-1,k.*r) ...
    - besselj(n+1,k.*r)).*exp(1j.*n.*phi).*sin(l.*z);
kadj2 = @(n, k, l, r, phi, z) (1./r).*(1j.*n).*besselj(n,k.*r).*...
    exp(1j.*n.*phi).*sin(l.*z);
kadj3 = @(n, k, l, r, phi, z) besselj(n,k.*r).*...
    exp(1j.*n.*phi).*l.*cos(l.*z);
kadj4 = @(n, k, l, r, phi, z) besselj(n,k.*r).*exp(1j.*n.*phi).*sin(l.*z);
end